# Generated by Django 3.2.13 on 2022-06-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0019_immutable_metadata_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptrepository',
            name='last_sync_details',
            field=models.JSONField(default=dict),
        ),
    ]
